/* LeetCode Hot 100 — 题目数据 */
var PROBLEMS = [
  {id:"1",slug:"two-sum",title:"两数之和",diff:"Easy",cat:"哈希",tags:["数组", "哈希表"],url:"https://leetcode.cn/problems/two-sum/"},
  {id:"49",slug:"group-anagrams",title:"字母异位词分组",diff:"Medium",cat:"哈希",tags:["数组", "哈希表", "字符串"],url:"https://leetcode.cn/problems/group-anagrams/"},
  {id:"128",slug:"longest-consecutive-sequence",title:"最长连续序列",diff:"Medium",cat:"哈希",tags:["并查集", "数组", "哈希表"],url:"https://leetcode.cn/problems/longest-consecutive-sequence/"},
  {id:"283",slug:"move-zeroes",title:"移动零",diff:"Easy",cat:"双指针",tags:["数组", "双指针"],url:"https://leetcode.cn/problems/move-zeroes/"},
  {id:"11",slug:"container-with-most-water",title:"盛最多水的容器",diff:"Medium",cat:"双指针",tags:["贪心", "数组", "双指针"],url:"https://leetcode.cn/problems/container-with-most-water/"},
  {id:"15",slug:"3sum",title:"三数之和",diff:"Medium",cat:"双指针",tags:["数组", "双指针", "排序"],url:"https://leetcode.cn/problems/3sum/"},
  {id:"42",slug:"trapping-rain-water",title:"接雨水",diff:"Hard",cat:"双指针",tags:["栈", "数组", "双指针", "动态规划"],url:"https://leetcode.cn/problems/trapping-rain-water/"},
  {id:"3",slug:"longest-substring-without-repeating-characters",title:"无重复字符的最长子串",diff:"Medium",cat:"滑动窗口",tags:["哈希表", "字符串", "滑动窗口"],url:"https://leetcode.cn/problems/longest-substring-without-repeating-characters/"},
  {id:"438",slug:"find-all-anagrams-in-a-string",title:"找到字符串中所有字母异位词",diff:"Medium",cat:"滑动窗口",tags:["哈希表", "字符串", "滑动窗口"],url:"https://leetcode.cn/problems/find-all-anagrams-in-a-string/"},
  {id:"560",slug:"subarray-sum-equals-k",title:"和为 K 的子数组",diff:"Medium",cat:"子串",tags:["数组", "哈希表", "前缀和"],url:"https://leetcode.cn/problems/subarray-sum-equals-k/"},
  {id:"239",slug:"sliding-window-maximum",title:"滑动窗口最大值",diff:"Hard",cat:"子串",tags:["队列", "数组", "滑动窗口", "单调队列", "堆"],url:"https://leetcode.cn/problems/sliding-window-maximum/"},
  {id:"76",slug:"minimum-window-substring",title:"最小覆盖子串",diff:"Hard",cat:"子串",tags:["哈希表", "字符串", "滑动窗口"],url:"https://leetcode.cn/problems/minimum-window-substring/"},
  {id:"53",slug:"maximum-subarray",title:"最大子数组和",diff:"Medium",cat:"普通数组",tags:["数组", "分治", "动态规划"],url:"https://leetcode.cn/problems/maximum-subarray/"},
  {id:"56",slug:"merge-intervals",title:"合并区间",diff:"Medium",cat:"普通数组",tags:["数组", "排序"],url:"https://leetcode.cn/problems/merge-intervals/"},
  {id:"189",slug:"rotate-array",title:"轮转数组",diff:"Medium",cat:"普通数组",tags:["数组", "数学", "双指针"],url:"https://leetcode.cn/problems/rotate-array/"},
  {id:"238",slug:"product-of-array-except-self",title:"除自身以外数组的乘积",diff:"Medium",cat:"普通数组",tags:["数组", "前缀和"],url:"https://leetcode.cn/problems/product-of-array-except-self/"},
  {id:"41",slug:"first-missing-positive",title:"缺失的第一个正数",diff:"Hard",cat:"普通数组",tags:["数组", "哈希表"],url:"https://leetcode.cn/problems/first-missing-positive/"},
  {id:"73",slug:"set-matrix-zeroes",title:"矩阵置零",diff:"Medium",cat:"矩阵",tags:["数组", "哈希表", "矩阵"],url:"https://leetcode.cn/problems/set-matrix-zeroes/"},
  {id:"54",slug:"spiral-matrix",title:"螺旋矩阵",diff:"Medium",cat:"矩阵",tags:["数组", "矩阵", "模拟"],url:"https://leetcode.cn/problems/spiral-matrix/"},
  {id:"48",slug:"rotate-image",title:"旋转图像",diff:"Medium",cat:"矩阵",tags:["数组", "数学", "矩阵"],url:"https://leetcode.cn/problems/rotate-image/"},
  {id:"240",slug:"search-a-2d-matrix-ii",title:"搜索二维矩阵 II",diff:"Medium",cat:"矩阵",tags:["数组", "二分查找", "分治", "矩阵"],url:"https://leetcode.cn/problems/search-a-2d-matrix-ii/"},
  {id:"160",slug:"intersection-of-two-linked-lists",title:"相交链表",diff:"Easy",cat:"链表",tags:["哈希表", "链表", "双指针"],url:"https://leetcode.cn/problems/intersection-of-two-linked-lists/"},
  {id:"206",slug:"reverse-linked-list",title:"反转链表",diff:"Easy",cat:"链表",tags:["递归", "链表"],url:"https://leetcode.cn/problems/reverse-linked-list/"},
  {id:"234",slug:"palindrome-linked-list",title:"回文链表",diff:"Easy",cat:"链表",tags:["栈", "递归", "链表", "双指针"],url:"https://leetcode.cn/problems/palindrome-linked-list/"},
  {id:"141",slug:"linked-list-cycle",title:"环形链表",diff:"Easy",cat:"链表",tags:["哈希表", "链表", "双指针"],url:"https://leetcode.cn/problems/linked-list-cycle/"},
  {id:"142",slug:"linked-list-cycle-ii",title:"环形链表 II",diff:"Medium",cat:"链表",tags:["哈希表", "链表", "双指针"],url:"https://leetcode.cn/problems/linked-list-cycle-ii/"},
  {id:"21",slug:"merge-two-sorted-lists",title:"合并两个有序链表",diff:"Easy",cat:"链表",tags:["递归", "链表"],url:"https://leetcode.cn/problems/merge-two-sorted-lists/"},
  {id:"2",slug:"add-two-numbers",title:"两数相加",diff:"Medium",cat:"链表",tags:["递归", "链表", "数学"],url:"https://leetcode.cn/problems/add-two-numbers/"},
  {id:"19",slug:"remove-nth-node-from-end-of-list",title:"删除链表的倒数第 N 个结点",diff:"Medium",cat:"链表",tags:["链表", "双指针"],url:"https://leetcode.cn/problems/remove-nth-node-from-end-of-list/"},
  {id:"24",slug:"swap-nodes-in-pairs",title:"两两交换链表中的节点",diff:"Medium",cat:"链表",tags:["递归", "链表"],url:"https://leetcode.cn/problems/swap-nodes-in-pairs/"},
  {id:"25",slug:"reverse-nodes-in-k-group",title:"K 个一组翻转链表",diff:"Hard",cat:"链表",tags:["递归", "链表"],url:"https://leetcode.cn/problems/reverse-nodes-in-k-group/"},
  {id:"138",slug:"copy-list-with-random-pointer",title:"随机链表的复制",diff:"Medium",cat:"链表",tags:["哈希表", "链表"],url:"https://leetcode.cn/problems/copy-list-with-random-pointer/"},
  {id:"148",slug:"sort-list",title:"排序链表",diff:"Medium",cat:"链表",tags:["链表", "双指针", "分治", "排序", "归并排序"],url:"https://leetcode.cn/problems/sort-list/"},
  {id:"23",slug:"merge-k-sorted-lists",title:"合并 K 个升序链表",diff:"Hard",cat:"链表",tags:["链表", "分治", "堆", "归并排序"],url:"https://leetcode.cn/problems/merge-k-sorted-lists/"},
  {id:"146",slug:"lru-cache",title:"LRU 缓存",diff:"Medium",cat:"链表",tags:["设计", "哈希表", "链表", "双向链表"],url:"https://leetcode.cn/problems/lru-cache/"},
  {id:"94",slug:"binary-tree-inorder-traversal",title:"二叉树的中序遍历",diff:"Easy",cat:"二叉树",tags:["栈", "树", "深度优先搜索", "二叉树"],url:"https://leetcode.cn/problems/binary-tree-inorder-traversal/"},
  {id:"104",slug:"maximum-depth-of-binary-tree",title:"二叉树的最大深度",diff:"Easy",cat:"二叉树",tags:["树", "深度优先搜索", "广度优先搜索", "二叉树"],url:"https://leetcode.cn/problems/maximum-depth-of-binary-tree/"},
  {id:"226",slug:"invert-binary-tree",title:"翻转二叉树",diff:"Easy",cat:"二叉树",tags:["树", "深度优先搜索", "广度优先搜索", "二叉树"],url:"https://leetcode.cn/problems/invert-binary-tree/"},
  {id:"101",slug:"symmetric-tree",title:"对称二叉树",diff:"Easy",cat:"二叉树",tags:["树", "深度优先搜索", "广度优先搜索", "二叉树"],url:"https://leetcode.cn/problems/symmetric-tree/"},
  {id:"543",slug:"diameter-of-binary-tree",title:"二叉树的直径",diff:"Easy",cat:"二叉树",tags:["树", "深度优先搜索", "二叉树"],url:"https://leetcode.cn/problems/diameter-of-binary-tree/"},
  {id:"102",slug:"binary-tree-level-order-traversal",title:"二叉树的层序遍历",diff:"Medium",cat:"二叉树",tags:["树", "广度优先搜索", "二叉树"],url:"https://leetcode.cn/problems/binary-tree-level-order-traversal/"},
  {id:"108",slug:"convert-sorted-array-to-binary-search-tree",title:"将有序数组转换为二叉搜索树",diff:"Easy",cat:"二叉树",tags:["树", "二叉搜索树", "数组", "分治", "二叉树"],url:"https://leetcode.cn/problems/convert-sorted-array-to-binary-search-tree/"},
  {id:"98",slug:"validate-binary-search-tree",title:"验证二叉搜索树",diff:"Medium",cat:"二叉树",tags:["树", "深度优先搜索", "二叉搜索树", "二叉树"],url:"https://leetcode.cn/problems/validate-binary-search-tree/"},
  {id:"230",slug:"kth-smallest-element-in-a-bst",title:"二叉搜索树中第 K 小的元素",diff:"Medium",cat:"二叉树",tags:["树", "深度优先搜索", "二叉搜索树", "二叉树"],url:"https://leetcode.cn/problems/kth-smallest-element-in-a-bst/"},
  {id:"199",slug:"binary-tree-right-side-view",title:"二叉树的右视图",diff:"Medium",cat:"二叉树",tags:["树", "深度优先搜索", "广度优先搜索", "二叉树"],url:"https://leetcode.cn/problems/binary-tree-right-side-view/"},
  {id:"114",slug:"flatten-binary-tree-to-linked-list",title:"二叉树展开为链表",diff:"Medium",cat:"二叉树",tags:["栈", "树", "深度优先搜索", "链表", "二叉树"],url:"https://leetcode.cn/problems/flatten-binary-tree-to-linked-list/"},
  {id:"105",slug:"construct-binary-tree-from-preorder-and-inorder-traversal",title:"从前序与中序遍历序列构造二叉树",diff:"Medium",cat:"二叉树",tags:["树", "数组", "哈希表", "分治", "二叉树"],url:"https://leetcode.cn/problems/construct-binary-tree-from-preorder-and-inorder-traversal/"},
  {id:"437",slug:"path-sum-iii",title:"路径总和 III",diff:"Medium",cat:"二叉树",tags:["树", "深度优先搜索", "二叉树"],url:"https://leetcode.cn/problems/path-sum-iii/"},
  {id:"236",slug:"lowest-common-ancestor-of-a-binary-tree",title:"二叉树的最近公共祖先",diff:"Medium",cat:"二叉树",tags:["树", "深度优先搜索", "二叉树"],url:"https://leetcode.cn/problems/lowest-common-ancestor-of-a-binary-tree/"},
  {id:"124",slug:"binary-tree-maximum-path-sum",title:"二叉树中的最大路径和",diff:"Hard",cat:"二叉树",tags:["树", "深度优先搜索", "动态规划", "二叉树"],url:"https://leetcode.cn/problems/binary-tree-maximum-path-sum/"},
  {id:"200",slug:"number-of-islands",title:"岛屿数量",diff:"Medium",cat:"图论",tags:["深度优先搜索", "广度优先搜索", "并查集", "数组", "矩阵"],url:"https://leetcode.cn/problems/number-of-islands/"},
  {id:"994",slug:"rotting-oranges",title:"腐烂的橘子",diff:"Medium",cat:"图论",tags:["广度优先搜索", "数组", "矩阵"],url:"https://leetcode.cn/problems/rotting-oranges/"},
  {id:"207",slug:"course-schedule",title:"课程表",diff:"Medium",cat:"图论",tags:["深度优先搜索", "广度优先搜索", "图", "拓扑排序"],url:"https://leetcode.cn/problems/course-schedule/"},
  {id:"208",slug:"implement-trie-prefix-tree",title:"实现 Trie (前缀树)",diff:"Medium",cat:"图论",tags:["设计", "字典树", "哈希表", "字符串"],url:"https://leetcode.cn/problems/implement-trie-prefix-tree/"},
  {id:"46",slug:"permutations",title:"全排列",diff:"Medium",cat:"回溯",tags:["数组", "回溯"],url:"https://leetcode.cn/problems/permutations/"},
  {id:"78",slug:"subsets",title:"子集",diff:"Medium",cat:"回溯",tags:["位运算", "数组", "回溯"],url:"https://leetcode.cn/problems/subsets/"},
  {id:"17",slug:"letter-combinations-of-a-phone-number",title:"电话号码的字母组合",diff:"Medium",cat:"回溯",tags:["哈希表", "字符串", "回溯"],url:"https://leetcode.cn/problems/letter-combinations-of-a-phone-number/"},
  {id:"39",slug:"combination-sum",title:"组合总和",diff:"Medium",cat:"回溯",tags:["数组", "回溯"],url:"https://leetcode.cn/problems/combination-sum/"},
  {id:"22",slug:"generate-parentheses",title:"括号生成",diff:"Medium",cat:"回溯",tags:["字符串", "动态规划", "回溯"],url:"https://leetcode.cn/problems/generate-parentheses/"},
  {id:"79",slug:"word-search",title:"单词搜索",diff:"Medium",cat:"回溯",tags:["数组", "字符串", "回溯", "矩阵"],url:"https://leetcode.cn/problems/word-search/"},
  {id:"131",slug:"palindrome-partitioning",title:"分割回文串",diff:"Medium",cat:"回溯",tags:["字符串", "动态规划", "回溯"],url:"https://leetcode.cn/problems/palindrome-partitioning/"},
  {id:"51",slug:"n-queens",title:"N 皇后",diff:"Hard",cat:"回溯",tags:["数组", "回溯"],url:"https://leetcode.cn/problems/n-queens/"},
  {id:"35",slug:"search-insert-position",title:"搜索插入位置",diff:"Easy",cat:"二分查找",tags:["数组", "二分查找"],url:"https://leetcode.cn/problems/search-insert-position/"},
  {id:"74",slug:"search-a-2d-matrix",title:"搜索二维矩阵",diff:"Medium",cat:"二分查找",tags:["数组", "二分查找", "矩阵"],url:"https://leetcode.cn/problems/search-a-2d-matrix/"},
  {id:"34",slug:"find-first-and-last-position-of-element-in-sorted-array",title:"在排序数组中查找元素的第一个和最后一个位置",diff:"Medium",cat:"二分查找",tags:["数组", "二分查找"],url:"https://leetcode.cn/problems/find-first-and-last-position-of-element-in-sorted-array/"},
  {id:"33",slug:"search-in-rotated-sorted-array",title:"搜索旋转排序数组",diff:"Medium",cat:"二分查找",tags:["数组", "二分查找"],url:"https://leetcode.cn/problems/search-in-rotated-sorted-array/"},
  {id:"153",slug:"find-minimum-in-rotated-sorted-array",title:"寻找旋转排序数组中的最小值",diff:"Medium",cat:"二分查找",tags:["数组", "二分查找"],url:"https://leetcode.cn/problems/find-minimum-in-rotated-sorted-array/"},
  {id:"4",slug:"median-of-two-sorted-arrays",title:"寻找两个正序数组的中位数",diff:"Hard",cat:"二分查找",tags:["数组", "二分查找", "分治"],url:"https://leetcode.cn/problems/median-of-two-sorted-arrays/"},
  {id:"20",slug:"valid-parentheses",title:"有效的括号",diff:"Easy",cat:"栈",tags:["栈", "字符串"],url:"https://leetcode.cn/problems/valid-parentheses/"},
  {id:"155",slug:"min-stack",title:"最小栈",diff:"Medium",cat:"栈",tags:["栈", "设计"],url:"https://leetcode.cn/problems/min-stack/"},
  {id:"394",slug:"decode-string",title:"字符串解码",diff:"Medium",cat:"栈",tags:["栈", "递归", "字符串"],url:"https://leetcode.cn/problems/decode-string/"},
  {id:"739",slug:"daily-temperatures",title:"每日温度",diff:"Medium",cat:"栈",tags:["栈", "数组", "单调栈"],url:"https://leetcode.cn/problems/daily-temperatures/"},
  {id:"84",slug:"largest-rectangle-in-histogram",title:"柱状图中最大的矩形",diff:"Hard",cat:"栈",tags:["栈", "数组", "单调栈"],url:"https://leetcode.cn/problems/largest-rectangle-in-histogram/"},
  {id:"215",slug:"kth-largest-element-in-an-array",title:"数组中的第K个最大元素",diff:"Medium",cat:"堆",tags:["数组", "分治", "快速选择", "堆", "排序"],url:"https://leetcode.cn/problems/kth-largest-element-in-an-array/"},
  {id:"347",slug:"top-k-frequent-elements",title:"前 K 个高频元素",diff:"Medium",cat:"堆",tags:["数组", "哈希表", "分治", "桶排序", "计数", "快速选择", "堆", "排序"],url:"https://leetcode.cn/problems/top-k-frequent-elements/"},
  {id:"295",slug:"find-median-from-data-stream",title:"数据流的中位数",diff:"Hard",cat:"堆",tags:["设计", "双指针", "数据流", "排序", "堆"],url:"https://leetcode.cn/problems/find-median-from-data-stream/"},
  {id:"121",slug:"best-time-to-buy-and-sell-stock",title:"买卖股票的最佳时机",diff:"Easy",cat:"贪心算法",tags:["数组", "动态规划"],url:"https://leetcode.cn/problems/best-time-to-buy-and-sell-stock/"},
  {id:"55",slug:"jump-game",title:"跳跃游戏",diff:"Medium",cat:"贪心算法",tags:["贪心", "数组", "动态规划"],url:"https://leetcode.cn/problems/jump-game/"},
  {id:"45",slug:"jump-game-ii",title:"跳跃游戏 II",diff:"Medium",cat:"贪心算法",tags:["贪心", "数组", "动态规划"],url:"https://leetcode.cn/problems/jump-game-ii/"},
  {id:"763",slug:"partition-labels",title:"划分字母区间",diff:"Medium",cat:"贪心算法",tags:["贪心", "哈希表", "双指针", "字符串"],url:"https://leetcode.cn/problems/partition-labels/"},
  {id:"70",slug:"climbing-stairs",title:"爬楼梯",diff:"Easy",cat:"动态规划",tags:["数学", "动态规划"],url:"https://leetcode.cn/problems/climbing-stairs/"},
  {id:"118",slug:"pascals-triangle",title:"杨辉三角",diff:"Easy",cat:"动态规划",tags:["数组", "动态规划"],url:"https://leetcode.cn/problems/pascals-triangle/"},
  {id:"198",slug:"house-robber",title:"打家劫舍",diff:"Medium",cat:"动态规划",tags:["数组", "动态规划"],url:"https://leetcode.cn/problems/house-robber/"},
  {id:"279",slug:"perfect-squares",title:"完全平方数",diff:"Medium",cat:"动态规划",tags:["广度优先搜索", "数学", "动态规划"],url:"https://leetcode.cn/problems/perfect-squares/"},
  {id:"322",slug:"coin-change",title:"零钱兑换",diff:"Medium",cat:"动态规划",tags:["广度优先搜索", "数组", "动态规划"],url:"https://leetcode.cn/problems/coin-change/"},
  {id:"139",slug:"word-break",title:"单词拆分",diff:"Medium",cat:"动态规划",tags:["数组", "哈希表", "字符串", "动态规划"],url:"https://leetcode.cn/problems/word-break/"},
  {id:"300",slug:"longest-increasing-subsequence",title:"最长递增子序列",diff:"Medium",cat:"动态规划",tags:["数组", "二分查找", "动态规划"],url:"https://leetcode.cn/problems/longest-increasing-subsequence/"},
  {id:"152",slug:"maximum-product-subarray",title:"乘积最大子数组",diff:"Medium",cat:"动态规划",tags:["数组", "动态规划"],url:"https://leetcode.cn/problems/maximum-product-subarray/"},
  {id:"416",slug:"partition-equal-subset-sum",title:"分割等和子集",diff:"Medium",cat:"动态规划",tags:["数组", "动态规划"],url:"https://leetcode.cn/problems/partition-equal-subset-sum/"},
  {id:"32",slug:"longest-valid-parentheses",title:"最长有效括号",diff:"Hard",cat:"动态规划",tags:["栈", "字符串", "动态规划"],url:"https://leetcode.cn/problems/longest-valid-parentheses/"},
  {id:"62",slug:"unique-paths",title:"不同路径",diff:"Medium",cat:"多维动态规划",tags:["数学", "动态规划", "组合数学"],url:"https://leetcode.cn/problems/unique-paths/"},
  {id:"64",slug:"minimum-path-sum",title:"最小路径和",diff:"Medium",cat:"多维动态规划",tags:["数组", "动态规划", "矩阵"],url:"https://leetcode.cn/problems/minimum-path-sum/"},
  {id:"5",slug:"longest-palindromic-substring",title:"最长回文子串",diff:"Medium",cat:"多维动态规划",tags:["字符串", "动态规划"],url:"https://leetcode.cn/problems/longest-palindromic-substring/"},
  {id:"1143",slug:"longest-common-subsequence",title:"最长公共子序列",diff:"Medium",cat:"多维动态规划",tags:["字符串", "动态规划"],url:"https://leetcode.cn/problems/longest-common-subsequence/"},
  {id:"72",slug:"edit-distance",title:"编辑距离",diff:"Medium",cat:"多维动态规划",tags:["字符串", "动态规划"],url:"https://leetcode.cn/problems/edit-distance/"},
  {id:"136",slug:"single-number",title:"只出现一次的数字",diff:"Easy",cat:"技巧",tags:["位运算", "数组"],url:"https://leetcode.cn/problems/single-number/"},
  {id:"169",slug:"majority-element",title:"多数元素",diff:"Easy",cat:"技巧",tags:["数组", "哈希表", "分治", "计数", "排序"],url:"https://leetcode.cn/problems/majority-element/"},
  {id:"75",slug:"sort-colors",title:"颜色分类",diff:"Medium",cat:"技巧",tags:["数组", "双指针", "排序"],url:"https://leetcode.cn/problems/sort-colors/"},
  {id:"31",slug:"next-permutation",title:"下一个排列",diff:"Medium",cat:"技巧",tags:["数组", "双指针"],url:"https://leetcode.cn/problems/next-permutation/"},
  {id:"287",slug:"find-the-duplicate-number",title:"寻找重复数",diff:"Medium",cat:"技巧",tags:["位运算", "数组", "双指针", "二分查找"],url:"https://leetcode.cn/problems/find-the-duplicate-number/"},
];